### ISSUE TITLE
Incompatible with Uglifyjs

### ISSUE THREAD

**Issue by chuangbo** [alexsasharegan/vue-transmit#1]
## Issue
Cannot be built for production with Uglify enabled.

## Expected
Works with Uglify

## Reproduce

```sh
$ vue init webpack-simple vue-webpack-simple
$ cd vue-webpack-simple
$ npm install
$ npm install --save-dev vue-transmit
```

Add vue-transmit to src/main.js

```js
import VueTransmit from 'vue-transmit'
Vue.use(VueTransmit)
```

Build

```sh
$ npm run build
ERROR in build.js from UglifyJs
Unexpected token: name (t) [./~/vue-transmit/dist/vue-transmit.esm.min.js:1,1289][build.js:96,1293]
```

**Comment by chuangbo** [comment]
It seems like Uglify works with es5 syntax only, I tried to just use `presets: ["es2015"]` (same as Vue) and it works

**Comment by alexsasharegan** [comment]
A couple things here:

- Basically yes, uglify is still stuck at es5 compatibility.
- If you're using es6 in your project, you'll pull the es module version of the lib. My bundling preset may leave a lot of the es6 syntax in the output (like object shorthands), but I've compiled most of the language features to es5 (minus certain built-ins on the Array prototype).

I recommend using [`babel-minify-webpack-plugin`](https://github.com/webpack-contrib/babel-minify-webpack-plugin) for es6 minification. The downside to using uglify and an es5 preset is that your target demographic may not require that much transpilation.

**Comment by chuangbo** [comment]
Thanks for the reply.

Since `vue init webpack` and [Laravel](https://github.com/JeffreyWay/laravel-mix/blob/8ec33a3b7522e14658650fb9ee8c83093557cd13/src/builder/webpack-plugins.js#L9)  use uglify for production by default, are you sure it's ok to drop support for those community?

**Comment by alexsasharegan** [comment]
This library is intended to be a modern JS library that takes full advantage of ES2015/ES6. The support for modern JS across browsers is excellent, and only getting better. I use the babel present env, and due to the current level of browser support, much of the ES2015 syntax makes it into the final build.

I see UglifyJS' lack of support for ES2015 as a problem, and a burden I don't intend to take on. They have a pretty impressive amount of optimizations, so I certainly sympathize with the sheer effort to get up to speed with ES2015, but if they don't catch up soon, other projects will start switching their minifier.

I think the best answer for this project is to include a fully ES5 build. That isn't my personal recommendation because it doesn't yield the best results (for size and optimizations), but I think it's a good workaround.

**Comment by alexsasharegan** [comment]
Try upgrading to `v5.3.0` and use the commonjs bundle. Let me know if this passes through UglifyJS 👌 

```js
import VueTransmit from "vue-transmit/dist/vue-transmit.common.min.js"
Vue.use(VueTransmit)
```

**Comment by chuangbo** [comment]
The same. Uglify can't recognize such as `const`, `let` and `{ foo() {} }` etc.

**Comment by alexsasharegan** [comment]
Working on getting babel to obey the config. Isn't transpiling `let|const` no matter what I throw at it.

**Comment by alexsasharegan** [comment]
Alright, I believe I've corrected everything. It turns out I need to indicate `babelrc:false` in the webpack config. I believe you've helped correct the builds for each target, so thank you for bringing this to my attention!

Go ahead and upgrade to `v5.3.1` and tell me how she does.

**Comment by chuangbo** [comment]
Many thanks. 5.3.2 works for me. 

PS: babel-minify-webpack-plugin works too 👍

**Comment by alexsasharegan** [comment]
Sorry for that! Check out `7.1.2` and see if that works for you. It looks like I missed the entry point file when I worked on 6.0 on.

**Comment by haleksandre** [comment]
Wow that was quick!

Looks good!  Thank you!  :+1:

**Comment by alexsasharegan** [comment]
Awesome! I use this in production, so this might have been affecting some of my users on older browsers!
