### ISSUE TITLE
Preventing upload on error/wrong file type

### ISSUE THREAD

**Issue by irjayjay** [alexsasharegan/vue-transmit#36]
I have the following set in my options, but it seems that returning false does not prevent an upload.

```
   acceptedFileTypes: ['image/*'],
   errInvalidFileType(type, _acceptedTypes, _file) {
       console.log(type)
       console.log(_acceptedTypes)
       return false
       console.log(_file)
  },
```

Where can I add any logic for preventing uploads?

**Comment by alexsasharegan** [comment]
Two things: first take care not to have statements after a return because they won't be executed. Second, the function you specified is used for generating an error message for that given error, not for determining whether or not a file should be accepted. I believe the function you want is the `accept` function. Returning a truthy value will sent a file. This is akin to the Nodejs error callback style.

**Comment by alexsasharegan** [comment]
Also, wherever you see underscore named params to a function signature, that's just me specifying the full signature, but marking the params as unused so typescript won't complain at compile time. It would normally fail to compile due to unused params, but adding underscores allows me to show off the extra params and still compile.

**Comment by alexsasharegan** [comment]
Another thing, accepted file types can be a global mime type like the example you have, an array of specific mime types, or an array of file extensions.

**Comment by irjayjay** [comment]
Apologies, I was in a rush and debugging, so I threw in a return false, assuming a return of false would stop execution on an upload. I know statements after a return aren't executed.

Great, so the accept function, does it get fed as part of the options as in the example above with the errInvalidFileType()?

Also, how can I find the params it accepts? 
I guess I could just add the function and console.log dummy params to figure it out, but is there a way of knowing before doing this:

accept(param1, param2, param3) {
    console.log(param1)
    console.log(param2)
    console.log(param3)
}

**Comment by alexsasharegan** [comment]
Looks like when I automated a doc update I blew away some of the descriptions. Here's the source: https://github.com/alexsasharegan/vue-transmit/blob/master/src/components/VueTransmit.vue

The accept function receives a VTransmitFile instance and the done callback. You do pass along with the other options.

**Comment by alexsasharegan** [comment]
I added better descriptions of the props in the readme. It now shows function signatures. There's also a table of contents to jump to sections on the page.
