### ISSUE TITLE
How to run a custom hook right before each upload?

### ISSUE THREAD

**Issue by ronny332** [alexsasharegan/vue-transmit#40]
Hi!

Vue-Transmit looks well structured and I'm impressed about the features (I'm running the currently latest version 9 alpha 11).

What I'm missing is a function which gets called right before each upload, just to set some params (and maybe a different url) which have to be unique per file.

I tried tried to manipulate the adapterData setter and getter of the file object, tried to create a custom XHRUploadAdapter which should run per request, but until now without any luck.

Watching at the source code I can't even figure out if different urls and params are a planned feature of this library.

Can anybody please clarify what I'm missing or if it is not possible in the current state of the library?

edit:
ok, as usual, right after creating a report, I found this topic: https://github.com/alexsasharegan/vue-transmit/issues/15

As seen there it is possible to modify the request, and I have seen the chance to fetch the event earlier. But modifying anything without knowing if the following action got already started (in this case the ajax request) doesn't sound like a good idea.

**Comment by alexsasharegan** [comment]
Thanks for trying out Vue Transmit! There is an event that fires right before an upload: `processing`. My suggestion to you is to attach a listener to this event and then mutate your adapter options. Since the `processing` event is fired directly before upload begins, your dynamic data will be used to process the upload. Note that async fetching won't be allowed here since the upload will begin synchronously after the `processing` handlers have been executed.

Here's a basic example of what it might look like:

```html
<template>
  <vue-transmit v-bind="options"
                @processing="onBeforeUpload" />
</template>

<script>
const url_base = `/api/upload`;

export default {
  data() {
    return {
      options: {
        acceptedFileTypes: ["image/*"],
        adapterOptions: {
          url: "",
          params: {},
          headers: {},
        },
      },
      files: [],
      showModal: false,
      error: "",
      count: 0,
    };
  },
  methods: {
    onBeforeUpload(vtFile) {
      this.params = {
        name: vtFile.name,
      };
      this.options.adapterOptions.url = `${url_base}/${vtFile.id}`;
    },
  },
};
</script>
```

Here is the event entry from the component events section of the docs:

![image](https://user-images.githubusercontent.com/16269252/37295050-6f2b8dda-25d4-11e8-9032-694d04c106b7.png)

I think you use case of dynamic urls and params is common enough that I will look into refactoring v9 to accept functions wherever dynamic content is possible.

**Comment by ronny332** [comment]
Hi,
thanks for your reply, that helped a lot.
It's hard to believe, but setting the url right before the request is starting works, even with a concurrency of 10 and 1kb files.

**Comment by alexsasharegan** [comment]
Glad it's working! This method is perfectly accurate, but it feels a little like a hack to me since it relies too much on internals (and a dev's knowledge of internals). I hope to get some time to work on v9 soon and make this story clearer and easier.

**Comment by alexsasharegan** [comment]
@ronny332, do you want to have a look at my changes to allow more ergonomic dynamic urls? The core idea is that each one of the xhr adapter options that was a static value can now also be a function that accepts an array of files to be processed (even when it's just one file per upload) and returns a static value. In other words, you can pass a string `url`, or a function that takes an array of files and returns a `url`.

With your current use case fresh in mind, would this be a nicer solution?

https://github.com/alexsasharegan/vue-transmit/blob/master/src/upload-adapters/xhr.ts#L29

**Comment by ronny332** [comment]
Hi,
generally I like this idea a lot. For my use case a bit more complex scenario is needed, but this will of cause help for the url.
In my case, the url and the params settings have to be variable, and, this is the main issue, at a certain point an asynchronous request has to be fired which fetches a param and a url (which both have to be used within the next request).
At this second I'm doing a kind of dirty trick to get between the `processFiles` method and the "processing" event (the `processFiles` method gets renamed to `_processFiles` globally and `processFiles` is a promised based method which fetches the session data and later on calls `_processFiles` which will continue the main functions of your module.
Of cause this will break completely if you change the code, but for now it is working :).

**Comment by alexsasharegan** [comment]
Okay, so what you want to do is turn off the auto processing. You can pass the option `autoQueue: false`, and use the `accepted-file` event to trigger all your async stuff. Once your async is done, call `enqueueFile` with the `VTransmitFile` instance and processing will start up. You can also pass `autoProcessQueue: false` and call `processQueue` manually. This will flush the queue (according to your max files) and begin processing.

There are a lot of places to short circuit the upload lifecycle and add async logic. This is still the architecture left over from Dropzone itself. I haven't found an ergonomic way to simplify this yet because each step in the lifecycle needs to be customizable.

**Comment by ronny332** [comment]
Yes, the auto processing is off until the first start. After the firstt start, I turn it on again, to let the module to its normal job (what saves a lot of work for handling the queue by my own). After the finish event was fired, auto processing is turned off again.

Please don't understand my words as "I would change", that's not the case. My use case will hit may be 1% of the developers (or even less?). The chance to create a hook is perfect and it looks like it is running very well until here.

**Comment by alexsasharegan** [comment]
👍 👍  Thanks for the feedback! I'm still trying to learn more about these dynamic use cases since I haven't been in that situation yet myself. I like your idea of flipping auto processing like a switch--clever idea. I think I still need more info (and maybe experience) before I can feel confident in an API change to add this functionality.

**Comment by ronny332** [comment]
You get your experience in combination with a job that forces you to learn things rapidly (that's what happened to me within the last 10 years). But enjoy your time "without experience which is the consequence of your job", afterwards you won't have the time any longer to produce modules like this one with this high amount of perfection and enthusiastic work ;-).

**Comment by alexsasharegan** [comment]
Haha totally feel you there, but that's not what I meant. I meant I don't have any experience with your use case. This whole project is born out of my job. I'm at a print company where I'm helping them pioneer their online, upload to order prints business. I need uploaders in every stinking app we make!
