### ISSUE TITLE
errorMessage attribute is blank on the timeout error

### ISSUE THREAD

**Issue by moltar** [alexsasharegan/vue-transmit#42]
The timeout event has a `errorMessage` attribute, but it has no message. Would be useful to have a generic interface to all of the errors. Thanks.

**Comment by alexsasharegan** [comment]
Generic interfaces are nice, but what message logically goes with a timeout? It's kind of like ascribing a message to `void`. I think it's best to leave that into the implementor's hands rather than put a generic message in there saying, `"Operation exceeded timeout"` or some such message. Thoughts?

**Comment by moltar** [comment]
Then maybe it should not fire the error event? Only the timeout event.

**Comment by alexsasharegan** [comment]
Hmm... looks like I forgot what I have set up. If you're running alpha 9, there's another function to return the message: https://github.com/alexsasharegan/vue-transmit/blob/master/src/upload-adapters/xhr.ts#L241-L251

**Comment by moltar** [comment]
I see, I think it is my bad. I was looking at the first param object, which has an `errorMessage` attribute, which is blank. The actual error message string is passed as the second param.

**Comment by alexsasharegan** [comment]
No worries!
